<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-PJ5JRQT" name="com.selenium.testng.TestNG_TimeOut" tests="1" failures="0" timestamp="19 Jan 2024 13:50:44 GMT" time="13.646" errors="1">
  <testcase name="test1" time="13.646" classname="com.selenium.testng.TestNG_TimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.selenium.testng.TestNG_TimeOut.test1() didn&#039;t finish within the time-out 4000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.selenium.testng.TestNG_TimeOut.test1() didn't finish within the time-out 4000
at java.lang.Thread.interrupt(Thread.java:919)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:64)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- test1 -->
</testsuite> <!-- com.selenium.testng.TestNG_TimeOut -->
